[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps =
  adafruit/DHT sensor library@^1.4.6
  arduino-libraries/LiquidCrystal@^1.0.7
build_flags =
  -Wl,-u,vfprintf
  -lprintf_flt
  -lm
